/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author dlmn5
 */
public class DLGPartida extends javax.swing.JDialog {

    /**
     * Creates new form DLGPartida
     *
     * @param parent
     * @param modal
     */
    public DLGPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

        this.panel.getRootPane().setOpaque(false);
        this.panel.setBackground(new Color(0, 0, 0, 0));

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        lblJ1Puntaje = new javax.swing.JLabel();
        lblJ1Nombre = new javax.swing.JLabel();
        lblJugador1Puntaje = new javax.swing.JLabel();
        lblJ2Puntaje = new javax.swing.JLabel();
        lblJ2Nombre = new javax.swing.JLabel();
        lblJugador2Puntaje = new javax.swing.JLabel();
        lblJ3Puntaje = new javax.swing.JLabel();
        lblJ3Nombre = new javax.swing.JLabel();
        lblJugador3Puntaje = new javax.swing.JLabel();
        lblJ4Puntaje = new javax.swing.JLabel();
        lblJ4Nombre = new javax.swing.JLabel();
        lblJugador4Puntaje = new javax.swing.JLabel();
        btnAbandonar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulo.png"))); // NOI18N
        panel.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 240, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCerrar.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 30, 30));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnMinimizar.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        panel.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 30, 30));

        lblJ1Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ1Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ1Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 60, 20));

        lblJ1Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ1Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ1Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1Nombre.setText("Jugador 1");
        panel.add(lblJ1Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 80, 30));

        lblJugador1Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador1Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 250, -1));

        lblJ2Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ2Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ2Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 60, 20));

        lblJ2Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ2Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ2Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Nombre.setText("Jugador 2");
        panel.add(lblJ2Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 80, 30));

        lblJugador2Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador2Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 250, -1));

        lblJ3Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ3Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ3Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 60, 20));

        lblJ3Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ3Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ3Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Nombre.setText("Jugador 3");
        panel.add(lblJ3Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 80, 30));

        lblJugador3Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador3Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 250, -1));

        lblJ4Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ4Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ4Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 60, 20));

        lblJ4Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ4Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ4Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Nombre.setText("Jugador 4");
        panel.add(lblJ4Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 80, 30));

        lblJugador4Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador4Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 250, -1));

        btnAbandonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAbandonar.png"))); // NOI18N
        btnAbandonar.setBorder(null);
        btnAbandonar.setBorderPainted(false);
        btnAbandonar.setContentAreaFilled(false);
        btnAbandonar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbandonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarActionPerformed(evt);
            }
        });
        panel.add(btnAbandonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 170, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 720, 450));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoDLG.png"))); // NOI18N
        panel.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1070, 690));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnAbandonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJ1Nombre;
    private javax.swing.JLabel lblJ1Puntaje;
    private javax.swing.JLabel lblJ2Nombre;
    private javax.swing.JLabel lblJ2Puntaje;
    private javax.swing.JLabel lblJ3Nombre;
    private javax.swing.JLabel lblJ3Puntaje;
    private javax.swing.JLabel lblJ4Nombre;
    private javax.swing.JLabel lblJ4Puntaje;
    private javax.swing.JLabel lblJugador1Puntaje;
    private javax.swing.JLabel lblJugador2Puntaje;
    private javax.swing.JLabel lblJugador3Puntaje;
    private javax.swing.JLabel lblJugador4Puntaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
