/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Graphics2D;

/**
 *
 * @author dlmn5
 */
public class DLGPartida extends javax.swing.JDialog {

    /**
     * Creates new form DLGPartida
     *
     * @param parent
     * @param modal
     */
    public DLGPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

        this.panel.getRootPane().setOpaque(false);
        this.panel.setBackground(new Color(0, 0, 0, 0));

        Color c = new Color(0, 0, 0, 0);
        this.panelJugador1.setBackground(c);
        this.panelJugador2.setBackground(c);
        this.panelJugador3.setBackground(c);
        this.panelJugador4.setBackground(c);
       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        colorJugador1 = new javax.swing.JButton();
        colorJugador2 = new javax.swing.JButton();
        colorJugador3 = new javax.swing.JButton();
        colorJugador4 = new javax.swing.JButton();
        panelJugador4 = new javax.swing.JPanel();
        panelJugador2 = new javax.swing.JPanel();
        panelJugador3 = new javax.swing.JPanel();
        panelJugador1 = new javax.swing.JPanel();
        inicia = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        lblJ1Puntaje = new javax.swing.JLabel();
        lblJ1Nombre = new javax.swing.JLabel();
        lblJugador1Puntaje = new javax.swing.JLabel();
        lblJ2Puntaje = new javax.swing.JLabel();
        lblJ2Nombre = new javax.swing.JLabel();
        lblJugador2Puntaje = new javax.swing.JLabel();
        lblJ3Puntaje = new javax.swing.JLabel();
        lblJ3Nombre = new javax.swing.JLabel();
        lblJugador3Puntaje = new javax.swing.JLabel();
        lblJ4Puntaje = new javax.swing.JLabel();
        lblJ4Nombre = new javax.swing.JLabel();
        lblJugador4Puntaje = new javax.swing.JLabel();
        btnAbandonar = new javax.swing.JButton();
        tablero = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colorJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador1.setBorder(null);
        colorJugador1.setBorderPainted(false);
        colorJugador1.setContentAreaFilled(false);
        colorJugador1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colorJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador1ActionPerformed(evt);
            }
        });
        panel.add(colorJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 50, 40));

        colorJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador2.setBorder(null);
        colorJugador2.setBorderPainted(false);
        colorJugador2.setContentAreaFilled(false);
        colorJugador2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colorJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador2ActionPerformed(evt);
            }
        });
        panel.add(colorJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 50, 40));

        colorJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador3.setBorder(null);
        colorJugador3.setBorderPainted(false);
        colorJugador3.setContentAreaFilled(false);
        colorJugador3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colorJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador3ActionPerformed(evt);
            }
        });
        panel.add(colorJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 50, 40));

        colorJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador4.setBorder(null);
        colorJugador4.setBorderPainted(false);
        colorJugador4.setContentAreaFilled(false);
        colorJugador4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colorJugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador4ActionPerformed(evt);
            }
        });
        panel.add(colorJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 50, 40));
        panel.add(panelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 384, 50, 50));
        panel.add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 244, 50, 50));
        panel.add(panelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 314, 50, 50));
        panel.add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 174, 50, 50));

        inicia.setText("Inicia");
        inicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaActionPerformed(evt);
            }
        });
        panel.add(inicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 110, 50));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulo.png"))); // NOI18N
        panel.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 240, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCerrar.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 30, 30));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnMinimizar.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        panel.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        lblJ1Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ1Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ1Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 60, 20));

        lblJ1Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ1Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ1Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1Nombre.setText("Jugador 1");
        panel.add(lblJ1Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 80, 30));

        lblJugador1Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador1Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 250, -1));

        lblJ2Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ2Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ2Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 60, 20));

        lblJ2Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ2Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ2Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Nombre.setText("Jugador 2");
        panel.add(lblJ2Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 80, 30));

        lblJugador2Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador2Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 250, -1));

        lblJ3Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ3Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ3Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 60, 20));

        lblJ3Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ3Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ3Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Nombre.setText("Jugador 3");
        panel.add(lblJ3Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 80, 30));

        lblJugador3Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador3Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 250, -1));

        lblJ4Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ4Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ4Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 60, 20));

        lblJ4Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ4Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ4Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Nombre.setText("Jugador 4");
        panel.add(lblJ4Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 80, 30));

        lblJugador4Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador4Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 250, -1));

        btnAbandonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAbandonar.png"))); // NOI18N
        btnAbandonar.setBorder(null);
        btnAbandonar.setBorderPainted(false);
        btnAbandonar.setContentAreaFilled(false);
        btnAbandonar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel.add(btnAbandonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 170, 50));

        tablero.setBackground(new java.awt.Color(255, 255, 255));
        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 700, 530));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BGNormal.png"))); // NOI18N
        panel.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void colorJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador1ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador1.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador1.paintComponents(g);
    }//GEN-LAST:event_colorJugador1ActionPerformed

    private void colorJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador2ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador2.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador2.paintComponents(g);
    }//GEN-LAST:event_colorJugador2ActionPerformed

    private void colorJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador3ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador3.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador3.paintComponents(g);
    }//GEN-LAST:event_colorJugador3ActionPerformed

    private void colorJugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador4ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador4.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador4.paintComponents(g);
    }//GEN-LAST:event_colorJugador4ActionPerformed

    private void iniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaActionPerformed
        pintaTablero(20);
    }//GEN-LAST:event_iniciaActionPerformed

    public void pintaTablero(int tam){
         //---------------------------------------------------

        Graphics2D g = (Graphics2D) tablero.getGraphics();
        int xL = 10;
        int xR = this.tablero.getWidth() - 20;
        int yT = 10;

        double distancia = Math.sqrt(Math.pow((xL - xR), 2) + Math.pow((yT - yT), 2));
        double dist = distancia / tam;

        for (int i = 0; i <= tam; i++) {
            for (int j = 0; j <= tam; j++) {
                g.fillOval((int) (xL + dist * j), (int) (yT + dist * i), 5, 5);
            }
        }

        this.tablero.paintComponents(g);

        //---------------------------------------------------
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton colorJugador1;
    private javax.swing.JButton colorJugador2;
    private javax.swing.JButton colorJugador3;
    private javax.swing.JButton colorJugador4;
    private javax.swing.JButton inicia;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJ1Nombre;
    private javax.swing.JLabel lblJ1Puntaje;
    private javax.swing.JLabel lblJ2Nombre;
    private javax.swing.JLabel lblJ2Puntaje;
    private javax.swing.JLabel lblJ3Nombre;
    private javax.swing.JLabel lblJ3Puntaje;
    private javax.swing.JLabel lblJ4Nombre;
    private javax.swing.JLabel lblJ4Puntaje;
    private javax.swing.JLabel lblJugador1Puntaje;
    private javax.swing.JLabel lblJugador2Puntaje;
    private javax.swing.JLabel lblJugador3Puntaje;
    private javax.swing.JLabel lblJugador4Puntaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    private javax.swing.JPanel panelJugador3;
    private javax.swing.JPanel panelJugador4;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
